Events UI 🖌️
ECellNitrr/ECellApp2021 pull request #110
Opened 2021-02-19 03:23 UTC by TreavVasu

## Fixes #64 

### Description
Events UI

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

![Screenshot_1613704752](https://user-images.githubusercontent.com/16835617/108453144-e6066280-728f-11eb-8f42-0c3bcd389cba.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

2021-02-19 06:55 UTC, werainkhatri requested changes
Try to make it as similar to the SpeakerScreen, widget decision wise, as possible.
1. Register Button Gradient does not match with the design
2. No need for a separate gradient button, as you have used it only once
3. Image frame does not look aligned on my phone.
    <img src="https://user-images.githubusercontent.com/44755140/108468033-21af2580-72ac-11eb-8316-0c711e2a53be.jpg" width="300">
4. Reduce padding b/w cards.
5. Time should be in HH:MM AM/PM
6. revert the splash.dart screen.

2021-02-19 06:55 UTC, werainkhatri commented on lib/screens/events/eventsCard.dart
> +import 'package:ecellapp/core/res/colors.dart';
🔴 
1. file name - `event_card.dart`
2. name of file and name of class in the file should be in sync. You shouldn't call the file `eventsCard` and the class inside, `EventCard`

2021-02-19 06:55 UTC, werainkhatri commented on lib/screens/events/eventsCard.dart
> +    return Container(
need for this container?

2021-02-19 06:55 UTC, werainkhatri commented on lib/screens/events/eventsCard.dart
> +                  // color: Colors.white,
?

2021-02-19 06:55 UTC, werainkhatri commented on lib/screens/events/eventsCard.dart
> +                    onPressed: () => {},
add a TODO

2021-02-20 12:02 UTC, TreavVasu commented
> Try to make it as similar to the SpeakerScreen, widget decision wise, as possible.
> 
>     1. Register Button Gradient does not match with the design
> 
>     2. No need for a separate gradient button, as you have used it only once
> 
>     3. Image frame does not look aligned on my phone.
>        <img alt="" width="300" src="https://user-images.githubusercontent.com/44755140/108468033-21af2580-72ac-11eb-8316-0c711e2a53be.jpg">
> 
>     4. Reduce padding b/w cards.
> 
>     5. Time should be in HH:MM AM/PM
> 
>     6. revert the splash.dart screen.

6.Done
5. They are using 24hr notation so keeping just HH: MM
4. Done 
3. My device falls in 0.5 <  probably slight error due to your falling for other case please give it a try and upload the SS
2. Done
1. Hope it does now.

2021-02-20 12:05 UTC, TreavVasu commented
![Screenshot_1613821710](https://user-images.githubusercontent.com/16835617/108594797-0a526400-73a2-11eb-805d-17ad6b4c6e7c.png)

2021-02-20 12:27 UTC, werainkhatri commented
<img src="https://user-images.githubusercontent.com/44755140/108595275-f9572200-73a4-11eb-83b2-2d2293d1dcb3.jpg" width="300">
1. Bottom left, white card is shown
2. little space b/w image frame and text
3. register button's gradient looks wierd

2021-02-20 12:33 UTC, TreavVasu commented
> <img alt="" width="300" src="https://user-images.githubusercontent.com/44755140/108595275-f9572200-73a4-11eb-83b2-2d2293d1dcb3.jpg">
> 
>     1. Bottom left, white card is shown
> 
>     2. little space b/w image frame and text
> 
>     3. register button's gradient looks wierd

On it 3. will take a bit of time will do the update in the next commit

2021-02-20 14:54 UTC, TreavVasu commented
> > ```
> > 1. Bottom left, white card is shown
> > 
> > 2. little space b/w image frame and text
> > 
> > 3. register button's gradient looks wierd
> > ```
> 
> On it 3. will take a bit of time will do the update in the next commit

![Screenshot_1613832839](https://user-images.githubusercontent.com/16835617/108599856-9e7bf580-73b9-11eb-944a-4ec05db45dc6.png)

2021-02-20 16:30 UTC, TreavVasu commented
Final Build :

![WhatsApp Image 2021-02-20 at 9 59 42 PM](https://user-images.githubusercontent.com/16835617/108602255-08e76280-73c7-11eb-87d2-247c010f25a9.jpeg)

2021-02-21 13:12 UTC, TreavVasu commented
I think that it's good enough for the aspect ratio to work but I am not sure for devices <0.5 
- I cannot do anything but guess so I am using heightFactor for fonts as for some device it was giving overflow but it is resolved. 
- It and seems good enough to me (I know with the conversation with you but the ratio isn't good enough I think because for the same device falling into same >0.5 there was still giving the overflow.
- So using hybrid of both i.e. both are used 
- I don't know about positioned element location for ratio<0.5 device (would prefer to change it to heightFactor though)

2021-02-21 15:16 UTC, werainkhatri commented
TreavVasu#4

2021-02-21 16:06 UTC, werainkhatri approved these changes

2021-02-21 16:06 UTC, merged