Loading Screen added
ECellNitrr/ECellApp2021 pull request #112
Opened 2021-02-22 04:36 UTC by Hard-Coder05

## Fixes #101 

### Description

**Type of Change:** (Delete irrelevant options)
- Code 
- User Interface 

**Code/Quality Assurance Only** (Delete irrelevant options)
 
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

tested locally

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-23 09:33 UTC, werainkhatri requested changes
1. remove loading_screen.dart
2. move the background widget from `buildSuccess` to `build`
3. add the ecellanimation to buildLoading
4. test it in all the screen once
5. revert pubspec.lock changes

2021-02-24 12:45 UTC, Hard-Coder05 commented
@werainkhatri Done from my side

2021-02-24 17:04 UTC, werainkhatri requested changes

2021-02-24 17:04 UTC, werainkhatri commented on lib/screens/events/events.dart
> +    );
Single widget in stack can be replaced with just the element widget. Do the changes in other screens too.
```suggestion
    return Center(child: ECellLogoAnimation(size: width / 2));
```

2021-02-24 17:04 UTC, werainkhatri commented on lib/screens/forgot_password/forgot_password.dart
> +          );
whats the difference b/w this and the previous code?

2021-02-24 17:04 UTC, werainkhatri commented on lib/screens/sponsors/sponsors.dart
> +              if (state is SponsorsError) _buildAskReload(),
if...else it

2021-02-25 08:14 UTC, werainkhatri approved these changes

2021-02-25 08:14 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +                  }())),
```suggestion
                  child: () {
                    if (state is SpeakerInitial)
                      return _buildLoading(context);
                    else if (state is SpeakerSuccess)
                      return _buildSuccess(context, state.speakerList);
                    else if (state is SpeakerLoading)
                      return _buildLoading(context);
                    else
                      return _buildAskReload();
                  }(),
```

2021-02-25 08:17 UTC, merged