Error screen UI🖌️
ECellNitrr/ECellApp2021 pull request #113
Opened 2021-02-22 10:52 UTC by TreavVasu

## Fixes #102 

### Description
Introduces Error Screen with Retry button

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Emulator Preview 
![Screenshot_1613990338](https://user-images.githubusercontent.com/16835617/108698165-d4d88280-7529-11eb-96f3-5c7d70feb50d.png)
Real Device Preview 
![WhatsApp Image 2021-02-22 at 4 17 11 PM](https://user-images.githubusercontent.com/16835617/108698274-f6d20500-7529-11eb-80b8-ee6320ec9d2a.jpeg)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

2021-02-22 11:09 UTC, TreavVasu commented
- UI Approved by Design Team

2021-02-23 09:20 UTC, werainkhatri requested changes
1. Make it a widget
2. add a function as a argument to call when retry button is pressed.
3. add it to all the screens with retry state and test them once

2021-02-26 13:53 UTC, TreavVasu commented
Summary of Changes :
- [x] Discarded use of scroll controller in events and speaker.

2021-02-27 04:52 UTC, werainkhatri approved these changes

2021-02-27 04:55 UTC, merged