Nav bar about us 🖌️
ECellNitrr/ECellApp2021 pull request #121
Opened 2021-03-02 23:40 UTC by TreavVasu

## Fixes #52 

### Description

Fix for #52

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

![Screenshot_1614728394](https://user-images.githubusercontent.com/16835617/109729960-bb48d200-7bde-11eb-8c84-5d5956769504.png)
![Screenshot_1614728397](https://user-images.githubusercontent.com/16835617/109729965-bd129580-7bde-11eb-8607-9855868c2a80.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

2021-03-02 23:43 UTC, TreavVasu commented
Would Resolve icons soon.

2021-03-03 22:07 UTC, TreavVasu commented
![Screenshot_1614809228](https://user-images.githubusercontent.com/16835617/109878919-eee93200-7c9a-11eb-8329-b210c1732f15.png)
![Screenshot_1614809232](https://user-images.githubusercontent.com/16835617/109878922-f0b2f580-7c9a-11eb-8695-099bc367f09d.png)

2021-03-05 13:04 UTC, werainkhatri requested changes
1. navbar icons does not match with design.
2. add route to about us in menuscreen
3. merge main branch
4. remove pubspec.lock changes

2021-03-07 05:46 UTC, TreavVasu commented
![Screenshot_1615095242](https://user-images.githubusercontent.com/16835617/110230375-7f8f6e80-7f36-11eb-9690-3d63933a1ced.png)
![Screenshot_1615095246](https://user-images.githubusercontent.com/16835617/110230377-81593200-7f36-11eb-90eb-5c2b8a8b8115.png)

2021-03-08 18:03 UTC, werainkhatri approved these changes
1. Revert pubspec.lock
2. give better asset file names.
3. see how bottom nav bar buttons are implemented in HomeScreen and do the same.

2021-03-08 18:03 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +        SafeArea(child: tabs[_currentIndex]),
Is there a need for SafeArea?

2021-03-08 18:03 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +        ScreenBackground(elementId: 0),
remove ScreenBackground from here as there is ScreenBackground in Aim and Team

2021-03-08 18:03 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +                        Colors.pink[300],
Copy the gradient from home.dart. This looks a bit off.

2021-03-08 18:03 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +                  height: 55,
set height to 50

2021-03-08 18:05 UTC, werainkhatri commented
Wrongly approved. Do the changes and I'll merge it.

2021-03-08 18:23 UTC, TreavVasu commented
![Screenshot_1615227485](https://user-images.githubusercontent.com/16835617/110364206-7d79fc80-8069-11eb-8b39-8314fcb916ec.png)
![Screenshot_1615227490](https://user-images.githubusercontent.com/16835617/110364212-7fdc5680-8069-11eb-81f7-f1aebaee9d98.png)

2021-03-09 06:50 UTC, werainkhatri commented
No need to add images everytime you make changes. And do all the changes or talk to me if you have any doubt.

2021-03-09 07:12 UTC, werainkhatri approved these changes

2021-03-09 07:12 UTC, merged