Signup cubit
ECellNitrr/ECellApp2021 pull request #15
Opened 2021-01-11 19:14 UTC by Hard-Coder05

Solves #4 .
Testing has been done locally. Works well and fine.

2021-01-11 20:12 UTC, werainkhatri requested changes
Nice work!
Make sure to update the dart line length to 100 (VSCode:-Settings -> search "dart line length", Android Studio:-Settings -> Editor -> Code Style -> Dart -> Line Length) and format all the files to this new line length.

2021-01-11 20:12 UTC, werainkhatri commented on lib/core/res/errors.dart
> +class NetworkError extends Error {}
implement Exception instead of extending Error
Call it NetworkException

2021-01-11 20:12 UTC, werainkhatri commented on lib/core/res/strings.dart
> +  static const String networkError = "Couldn't register. Is the device online?";
rename to networkException
since it is named as a general network exception, it should have a general exception message, like "request couldn't be completed. make sure the device is online" or something. search the internet for good messages.

2021-01-11 20:12 UTC, werainkhatri commented on lib/main.dart
> +class Ecell extends StatelessWidget {
rename to **ECellApp**

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/signup.dart
> +              child: FirstName(firstNameController),
Have only one **NameField** instead of FirstName and LastName.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/signup.dart
> +          }
Always add TODOs wherever necessary.
```suggestion
          } if (state is SignupSuccess) {
              // TODO add on success logic
          }
```

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/signup.dart
> +                content: Text(state.message),
Try to lower the number of lines of code. It helps in easier code navigation and debugging.
```suggestion
                content: Text(state.message)
```
By removing this comma and formatting, the number of lines reduced by 2.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/signup.dart
> +          mobileController.hashCode);
**hashcode** is very very different from **text**. If you wish to know more, lemme know.
Fix the bug.
```suggestion
          mobileController.text);
```
You also need to convert the text (string) to int.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/first_name_field.dart
> +class FirstName extends StatelessWidget {
change this to NameField

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/first_name_field.dart
> +        labelText: "First Name",
```suggestion
        labelText: "Full Name",
```

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/first_name_field.dart
> +        hintText: "Enter your first name",
no need for hint text.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/last_name_field.dart
> +import 'package:flutter/material.dart';
remove this file.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/mobile_number_field.dart
> +class MobileNumber extends StatelessWidget {
maintain consistency. all similar widgets' names end with Field, except for this one.
```suggestion
class MobileNumberField extends StatelessWidget {
```

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/email_field.dart
> +        hintText: "example@email.com",
no need for hint text.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/mobile_number_field.dart
> +        hintText: "Enter your 10 digit mobile number",
no need for hint text.

2021-01-11 20:12 UTC, werainkhatri commented on lib/screens/signup/widgets/password_field.dart
> +          hintText: "p@ssw0rd",
no need for hint text.

2021-01-11 20:12 UTC, werainkhatri commented on pubspec.yaml
> +  http: ^0.12.1
don't add packages that you are not actually using right now.

2021-01-12 07:14 UTC, werainkhatri requested changes
General Instructions:
1. add screenshots whenever you work on UI elements.
2. Since this PR was supposed to solve a logic issue, it shouldn't have any UI elements. For now its fine, but in the future, all cubit issues should have only cubit and fake repo, ui issues should have UI only, and api issues only API wiring.
3. Don't resolve conversations on your PR review. the reviewer (in this case, me) resolve them as I re-review.
4. If you have any doubts in any conversation, message out in it.

2021-01-12 07:14 UTC, werainkhatri commented on lib/core/res/errors.dart
> +class NetworkException extends Error {}
```suggestion
class NetworkException implements Exception {}
```
This is what you are supposed to do.

2021-01-12 07:15 UTC, werainkhatri commented on lib/screens/signup/signup.dart
> +          }
this is also not done yet, and you resolved it anyway...

2021-01-12 08:07 UTC, Hard-Coder05 commented on lib/core/res/errors.dart
> +class NetworkException extends Error {}
done!

2021-01-12 14:10 UTC, werainkhatri approved these changes

2021-01-12 14:11 UTC, merged