Home UI
ECellNitrr/ECellApp2021 pull request #92
Opened 2021-02-12 16:07 UTC by Hard-Coder05

## Fixes #58 

### Description

Home UI 

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

tested locally

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-13 10:33 UTC, werainkhatri commented
Missing UI video/screenshots! Always add these when doing a UI PR.

2021-02-14 04:52 UTC, Hard-Coder05 commented
https://user-images.githubusercontent.com/54059881/107868913-73bc0980-6eae-11eb-9c0f-df5884dcf589.mp4

2021-02-14 13:59 UTC, werainkhatri commented
Is the softcoding of dimensions implemented?

2021-02-15 05:58 UTC, Hard-Coder05 commented
@werainkhatri Done everything. The PR is up for review. Also I have done all the editing as asked by Mohit.

https://user-images.githubusercontent.com/54059881/107910649-d8e02f80-6f80-11eb-9697-c5b6dc328aee.mp4

2021-02-15 08:12 UTC, werainkhatri requested changes

2021-02-15 08:12 UTC, werainkhatri commented on lib/screens/home/tabs/menu/menu.dart
> +    Log.i(tag: "Screen width: ", message: width.toString());
```suggestion
```

2021-02-15 08:13 UTC, werainkhatri approved these changes

2021-02-15 08:14 UTC, werainkhatri commented
Good work

2021-02-15 08:15 UTC, werainkhatri approved these changes

2021-02-15 08:15 UTC, werainkhatri commented on lib/screens/home/tabs/menu/menu.dart
> +import 'package:ecellapp/core/utils/logger.dart';
```suggestion
```

2021-02-15 08:26 UTC, merged