Feedback cubit
ECellNitrr/ECellApp2021 pull request #93
Opened 2021-02-14 04:51 UTC by Hard-Coder05

## Fixes #44 

### Description

Made the feedback cubit.

**Type of Change:** (Delete irrelevant options)
- Code

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Tested locally.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-14 16:34 UTC, werainkhatri commented
Its failing ci checks.

2021-02-14 16:59 UTC, Hard-Coder05 commented
> Its failing ci checks.

Its working now!

2021-02-14 18:01 UTC, werainkhatri requested changes
LGTM

2021-02-14 18:01 UTC, werainkhatri commented on lib/screens/home/cubit/feedback_state.dart
> +@immutable
reason for calling it `@immutable`?

2021-02-15 04:09 UTC, Hard-Coder05 commented on lib/screens/home/cubit/feedback_state.dart
> +@immutable
Nothing

2021-02-15 04:16 UTC, Hard-Coder05 commented
@werainkhatri The PR is ready to get merged!

2021-02-15 04:46 UTC, werainkhatri approved these changes

2021-02-15 04:46 UTC, merged