Splash Screen
ECellNitrr/ECellApp2021 pull request #94
Opened 2021-02-15 06:48 UTC by Hard-Coder05

## Fixes #68 

### Description

Splash Screen UI and Logic

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Tested locally.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

https://user-images.githubusercontent.com/54059881/107914113-c4ebfc00-6f87-11eb-8edd-8d0e01a4175d.mp4

2021-02-15 08:02 UTC, werainkhatri requested changes
change the name of ECellAnimation widget file to `ecell_animation.dart`

2021-02-15 08:02 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +  final splashDelay = 3;
should be in `dimens.dart`

2021-02-15 08:02 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +  }
1. no need to create small functions and call them. place these lines in `initState` directly.
2. don't create unwanted variables
3. call the `init()` function of main.dart (line 9) here.
```suggestion
  _loadWidget() async {
    await init();
    Timer(Duration(seconds: splashDelay), navigationPage);
  }
```

2021-02-15 08:02 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +    String token = sharedPreferences.getString(S.tokenKey);
```suggestion
    String token = sl.get<SharedPreferences>().getString(S.tokenKey);
```

2021-02-15 08:02 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +    ));
```suggestion
    return Scaffold(
      body: Stack(
        children: [
          ScreenBackground(elementId: 0),
          Center(child: ECellLogoAnimation()),
        ],
      ),
    );
```

2021-02-15 08:02 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +    }
```suggestion
  Navigator.pushReplacement(
    context,
    MaterialPageRoute(
      builder: (_) => (token == null)
          ? BlocProvider(
              create: (_) => LoginCubit(APILoginRepository()),
              child: LoginScreen(),
            )
          : HomeScreen(),
    ),
  );
```

2021-02-15 14:02 UTC, Hard-Coder05 commented on lib/screens/splash/splash.dart
> +  final splashDelay = 3;
done

2021-02-15 14:05 UTC, Hard-Coder05 commented on lib/screens/splash/splash.dart
> +    String token = sharedPreferences.getString(S.tokenKey);
done

2021-02-15 14:05 UTC, Hard-Coder05 commented on lib/screens/splash/splash.dart
> +  }
done

2021-02-15 14:06 UTC, Hard-Coder05 commented on lib/screens/splash/splash.dart
> +    ));
done

2021-02-15 14:06 UTC, Hard-Coder05 commented on lib/screens/splash/splash.dart
> +    }
done

2021-02-16 04:43 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +  }
`1.` is not done yet.

2021-02-16 04:45 UTC, werainkhatri approved these changes

2021-02-16 04:45 UTC, werainkhatri commented on lib/screens/splash/splash.dart
> +    return Timer(Duration(seconds: D.splashDelay), navigationPage);
```suggestion
    Timer(Duration(seconds: D.splashDelay), navigationPage);
```

2021-02-16 05:02 UTC, merged