Speaker UI 🖌️
ECellNitrr/ECellApp2021 pull request #96
Opened 2021-02-15 22:00 UTC by TreavVasu

## Fixes #63 

### Description

Speaker UI

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

![Screenshot_1613425865](https://user-images.githubusercontent.com/16835617/107996803-43d44980-7007-11eb-866b-a43903c2828c.png)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

2021-02-15 22:05 UTC, TreavVasu commented
The Details that appear on click are still left to be done

2021-02-16 15:29 UTC, TreavVasu commented
> The Details that appear on click are still left to be done

Resolved

2021-02-16 15:34 UTC, TreavVasu commented
@werainkhatri This is the final look of what it would be like. Awaiting to be reviewed and merged.

2021-02-17 06:03 UTC, werainkhatri requested changes
Very good work! Some changes.
1. Rename `speakerCard.dart`: dart file naming convensions - lower case letters with words separated by `_`
2. Reduce horizontal (left & right) and space b/w speaker cards.
3. add the `Speakers` heading to the scroll view so that it gets scrolled too.

2021-02-17 06:03 UTC, werainkhatri commented on lib/core/res/colors.dart
> +  static final Color blendSocialIconColorTwo = Colors.black38;
use `static const` for pre-defined colors,
```suggestion
  static const Color blendSocialIconColorOne = Colors.black12;
  static const Color blendSocialIconColorTwo = Colors.black38;
```

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speakerCard.dart
> +                                throw UnknownException();
🔴 🔴 
NEVER THROW EXCEPTIONS IF YOU ARE NOT CATCHING THEM. You throw exceptions to catch them at some later point in code. There should be a snackbar and Log.e here.

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speakerCard.dart
> +                  left: 0,
use `Align` with alignment: `Alignment.topLeft` instead

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speakerCard.dart
> +                    //ADD NETWORK_IMAGE
is there a reason for adding these comments?

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +
🔴 
reason for creating a function instead of placing the SpeakerCard directly? Remove it.

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +    List<Widget> sL = [];
use better variable names

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +    });
Attempt to use labda functions wherever you can.
```suggestion
    speakerList.forEach((e) => sL.add(_cardsLoader(e)););
```

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +                ),
```suggestion
                SizedBox(height: heightFactor * 100),
```

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker.dart
> +                  ),
```suggestion
                  child: Column(children: sL),
```

2021-02-17 06:03 UTC, werainkhatri commented on pubspec.yaml
> +  url_launcher: ^5.7.10
add the `pubspec.lock` now as you have updated `pubspec.yaml`

2021-02-17 06:03 UTC, werainkhatri commented on lib/screens/speaker/speaker_repository.dart
> +import 'package:flutter/foundation.dart';
this import is not required. remove it.

2021-02-17 12:57 UTC, TreavVasu commented on lib/screens/speaker/speakerCard.dart
> +                    //ADD NETWORK_IMAGE
Easy to navigate and catchy to the eye 🕵️‍♂️

2021-02-17 15:09 UTC, TreavVasu commented
What should I keep as Failed to load pic? I suggest the above on (in case) 🙆‍♀️

2021-02-17 15:34 UTC, werainkhatri commented on lib/screens/speaker/speakerCard.dart
> +                    //ADD NETWORK_IMAGE
Cool Cool

2021-02-17 15:36 UTC, werainkhatri commented
> What should I keep as Failed to load pic? I suggest the above on (in case) ok_woman

Consult the designer. Update me on that

Also, update the image in the PR description with the latest screenshot.

2021-02-17 15:41 UTC, TreavVasu commented
It's the latest one

2021-02-17 16:07 UTC, werainkhatri requested changes
Expected vs Delivered
<img src="https://user-images.githubusercontent.com/44755140/108231710-0c30e300-7168-11eb-9ff9-0b7a7b17891a.png" width="500">

ToDo: Reduce padding further and don't make the inter-card distances variable (don't multiply with height factor). Let it be static.

2021-02-17 21:27 UTC, TreavVasu commented
> Expected vs Delivered
> <img alt="" width="500" src="https://user-images.githubusercontent.com/44755140/108231710-0c30e300-7168-11eb-9ff9-0b7a7b17891a.png">
> 
> ToDo: Reduce padding further and don't make the inter-card distances variable (don't multiply with height factor). Let it be static.

Done @werainkhatri

2021-02-17 22:43 UTC, werainkhatri requested changes
Changes:
1. make it so that the card expands when i click anywhere on the card and not only on the arrow.
2. align the speaker company to be vertically center
3. Padding above and below the `Speaker` text is still more than in the design.
4. Update font color of name, company and description from the design.
5. Reduce left padding
6. replace _buildInitial() with _buildLoading()

2021-02-17 22:43 UTC, werainkhatri commented on lib/screens/speaker/speaker_card.dart
> +    return Container(
need for this container?

2021-02-18 08:41 UTC, TreavVasu commented
> Changes:
> 
>     1. make it so that the card expands when i click anywhere on the card and not only on the arrow.
> 
>     2. align the speaker company to be vertically center
> 
>     3. Padding above and below the `Speaker` text is still more than in the design.
> 
>     4. Update font color of name, company and description from the design.
> 
>     5. Reduce left padding
> 
>     6. replace _buildInitial() with _buildLoading()

For 1 : I think It's already working that way see : 
[appdemo](https://appetize.io/app/6rxzyy28q0y61251krmft0ft9c?device=nexus5&scale=75&orientation=portrait&osVersion=8.1)

2021-02-18 09:50 UTC, TreavVasu commented
![Screenshot from 2021-02-18 15-09-36](https://user-images.githubusercontent.com/16835617/108338856-bb1efe80-71fc-11eb-9408-9d6eb0871361.png)

2021-02-18 10:20 UTC, werainkhatri requested changes
All looks good, just one problem to fix
* In fake repository, add 2 more speakers OR expand a card and see the screen. The `Speakers` text gets below the notification shade and screen does not scroll down.

2021-02-18 10:29 UTC, TreavVasu commented
> All looks good, just one problem to fix
> 
>     * In fake repository, add 2 more speakers OR expand a card and see the screen. The `Speakers` text gets below the notification shade and screen does not scroll down.

![Screenshot_1613644149](https://user-images.githubusercontent.com/16835617/108343738-4cdd3a80-7202-11eb-8a91-c84e09dae26f.png)

2021-02-18 18:41 UTC, werainkhatri commented
> ### How about this fix SafeArea over Scaffold?

No! the ui needs to scroll behind the notification shade

2021-02-18 20:13 UTC, TreavVasu commented
> > ### How about this fix SafeArea over Scaffold?
> 
> No! the ui needs to scroll behind the notification shade




![untitled](https://user-images.githubusercontent.com/16835617/108415599-c4878580-7253-11eb-9e64-561710fbf35e.gif)

2021-02-18 21:02 UTC, werainkhatri approved these changes
Good Work. 👍🏼 
Keep my code decisions (that I made in the PR) in mind while working in the future.

2021-02-18 21:06 UTC, merged