added about us bottom navigation bar
ECellNitrr/ECellApp2021 pull request #98
Opened 2021-02-16 06:04 UTC by divy-arpit

## Fixes #52 

### Description

Added bottom navigation bar for About Us Screen

**Type of Change:** (Delete irrelevant options)
- Code
- User Interface

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Tested on local machine.

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [X] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [X] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

2021-02-17 04:42 UTC, werainkhatri commented
As this is a UI PR, add a screenshot/video of the changes made.

2021-02-17 06:29 UTC, divy-arpit commented
okay. Will take care of this next time onwards.

2021-02-21 10:42 UTC, divy-arpit commented
Current UI
![Android Emulator - Pixel_4_XL_API_30_5554 21-02-2021 16_09_10](https://user-images.githubusercontent.com/61823356/108622540-7e067680-745f-11eb-90a6-6d684a46c22f.png)

2021-02-27 07:24 UTC, Hard-Coder05 commented
@divy-arpit Is this completed from your side?

2021-02-27 07:26 UTC, Hard-Coder05 commented
@werainkhatri sir please review this and close this one

2021-02-27 07:49 UTC, Hard-Coder05 requested changes
Please make these changes ASAp

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +            selectedItemColor: Colors.orange[900],
```selected item color``` is not to be used here. please see the design its a gradient. please refer the home screen bottom nav bar(I have done this in that issue) and make the changes here.

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +    double height1 = MediaQuery.of(context).size.height;
change ```height1``` as ```height```

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +            showUnselectedLabels: false,
why ```showUnselectedLabels``` is false when the design needs it to be true

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +        onPressed: () {
complete the ```onPressed``` this can be integrated now

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +  Widget backButton(double width, double height, double bottom, double heightFactor) {
don't make separate function for backButton add it directly in the app bar

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/tabs/aim.dart
> +  Widget aboutUsText(double width, double height, double bottom, double heightFactor) {
what is the need of``` height``` and ```bottom``` here

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/tabs/aim.dart
> +                    fontWeight: FontWeight.w500,
make this w400 or w300 as given in the design. Currently the text looks bold.

2021-02-27 07:49 UTC, Hard-Coder05 commented on lib/screens/about_us/about_us.dart
> +      padding: EdgeInsets.fromLTRB(width / 15, 0, 0, 0),
use .fromOnly() when you need to specify padding in only one direction. Keep this inmind from next PRs.

2021-02-27 07:50 UTC, werainkhatri requested changes
Do the changes as I told you in the meeting

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +          SafeArea(child: tabs[_currentIndex]),
don't add SafeArea. Do it as its done in home.dart

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +      borderRadius: BorderRadius.all(Radius.circular(height1 / 20)),
The bottom nav bar should have constant / static border radius. Coordinate with designer and add a const value. Same goes for you @Hard-Coder05 for home screen.

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +            showSelectedLabels: false,
it should show the selected label.

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/about_us.dart
> +          // to be implemented during screen integration.
`Navigator.pop(context);`
What more screen integration is needed?

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/tabs/aim.dart
> +      child: screenBody(context),
add screenbody here directly. no need to add multiple functions.

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/tabs/aim.dart
> +              visionTextSection(width, height, bottom, heightFactor),
add all function contents directly here.

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/tabs/aim.dart
> +      padding: EdgeInsets.only(left: width / 50),
should have constant padding, here and everywhere.

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/tabs/aim.dart
> +          padding: const EdgeInsets.fromLTRB(D.horizontalPadding, 0, D.horizontalPadding, 0),
add a top padding of `top` (MediaQuery.of(context).viewInsets.top) `+ 56` (height of appbar)

2021-02-27 07:50 UTC, werainkhatri commented on lib/screens/about_us/tabs/aim.dart
> +            text: TextSpan(
add common style here.

2021-03-03 22:09 UTC, closed without merging